---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  pre_tasks:
  
  - name: install updates
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes

  tasks:
    - name: Collect PCAP file from server
      fetch:
        src: /home/jozette/Documents/PCAP/captured.pcap
        dest: /home/jozette/CPE243/HOA8.1/pcap_dest/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Extract executable from PCAP file
      command: "tcpflow -r /home/jozette/CPE243/HOA8.1/pcap_dest/captured.pcap -o /home/jozette/CPE243/HOA8.1/pcap_out/"
      args:
        creates: /home/jozette/CPE243/HOA8.1/pcap_out/executable.exe
    - name: Debug .exe file
      command: "cat /home/jozette/CPE243/HOA8.1/pcap_out/report.xml"
      register: cat_output
      changed_when: false

    - debug:
        var: cat_output.stdout_lines
